apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: doom
    repo: helm/kubedoom
    version: '0.1.0'
    releaseName: doom
    namespace: kubedoom
    valuesFile: values.yaml
